### ISSUE TITLE
Java bytecode and APK patching

### ISSUE THREAD

**Issue by infodox** [secretsquirrel/the-backdoor-factory#26]
Would possibly be interesting to backdoor Java archives and suchlike (perhaps even APK files?) in the future.

See here: https://github.com/mveytsman/dilettante
https://github.com/funsecurity/apk_binder_script
https://github.com/dana-at-cp/backdoor-apk

**Comment by secretsquirrel** [comment]
https://github.com/secretsquirrel/the-backdoor-factory#the-backdoor-factory-is-no-longer-maintained-or-supported
