### ISSUE TITLE
Add Bound Imports Parsing and Patching

### ISSUE THREAD

**Issue by secretsquirrel** [secretsquirrel/the-backdoor-factory#42]
Bug found in parsing of imports where BDF does not support Bound Imports.

While bound imports are not common, adding support in BDF would be an interesting exercise.

**Comment by secretsquirrel** [comment]
Added check in BDF to not support Bound Imports - as in not patch the binary.

![image](https://cloud.githubusercontent.com/assets/1679850/7383136/d975fffe-ede7-11e4-956b-27e9eca1a651.png)

**Comment by Omardavinci** [comment]
I get the same bug.
```
	 Backdoor Factory
         Author:    Joshua Pitts
         Email:     the.midnite.runr[-at ]gmail<d o-t>com
         Twitter:   @midnite_runr
         IRC:       freenode.net #BDFactory
         
         Version:   3.4.2
         
[*] In the backdoor module
[*] Checking if binary is supported
[*] Gathering file info
[*] Reading win32 entry instructions
[!] No support for Bound Imports at this time
```
And i can make the same thing in assembly injecting code.

**Comment by secretsquirrel** [comment]
Congrats. I accept pull requests.

**Comment by secretsquirrel** [comment]
https://github.com/secretsquirrel/the-backdoor-factory#the-backdoor-factory-is-no-longer-maintained-or-supported
