### ISSUE TITLE
ego issues

### ISSUE THREAD

**Issue by ayhaga** [secretsquirrel/the-backdoor-factory#45]
being an as**ole doesn`t make you a high level programmer even if you are and this darwinian method when thinking someone is weak will get you nowhere just like the place the world is heading for right now , you could`ve just said you must have meant a different place everybody makes mistakes
thank you again

**Comment by secretsquirrel** [comment]
No.  It doesn't. 

However, learning to read error messages does keep one from being a dumbass.
