### ISSUE TITLE
Error during The Backdoor Factory execution

### ISSUE THREAD

**Issue by bofhx** [secretsquirrel/the-backdoor-factory#64]
Hi,
i look you literature and video for use BackDooor.factory anf i found 1 bug.
https://github.com/Veil-Framework/Veil-Evasion/issues/308#issuecomment-206579009
ChrisTruncer is fix it.

Now i have another problem. 
I'm new at this, pray to you to help. Tnx
![image 2016-04-07 at 10 12 44](https://cloud.githubusercontent.com/assets/18294719/14344669/50a8e444-fca9-11e5-9dc9-ee71591756ab.jpg)

**Comment by secretsquirrel** [comment]
Yeah. So don't use the -s flag in Veil. I suggest using BDF standalone. See the README.
