### ISSUE TITLE
.NET IL Patching

### ISSUE THREAD

**Issue by secretsquirrel** [secretsquirrel/the-backdoor-factory#71]
Because why not.

**Comment by secretsquirrel** [comment]
https://github.com/secretsquirrel/the-backdoor-factory/issues/60

**Comment by stuk0v** [comment]
any plans on implementing .net patching? got same error as well

**Comment by secretsquirrel** [comment]
I accept pull requests! Reference material: https://www.amazon.com/dp/B004FV4R36/ref=dp-kindle-redirect?_encoding=UTF8&btkr=1

**Comment by secretsquirrel** [comment]
https://github.com/secretsquirrel/the-backdoor-factory#the-backdoor-factory-is-no-longer-maintained-or-supported
