### ISSUE TITLE
install.sh missing -y on one apt-get command

### ISSUE THREAD

**Issue by jeffmcjunkin** [secretsquirrel/the-backdoor-factory#76]
https://github.com/secretsquirrel/the-backdoor-factory/blob/master/install.sh#L48

Please add `-y` so as to not hang :)

Awesome project btw!

**Comment by secretsquirrel** [comment]
@jeffmcjunkin it's already there.

```
if hash pip 2>/dev/null; then
		sudo apt-get install -y python-pip autoconf libtool curl libcurl4-openssl-dev
	        pip install pefile
```

**Comment by jeffmcjunkin** [comment]
Oops! Sorry, I highlighted the wrong line: https://github.com/secretsquirrel/the-backdoor-factory/blob/master/install.sh#L70

**Comment by secretsquirrel** [comment]
I wrote a Haiku for you:

My install script asks
Would you like this library
Ponder your being
