### ISSUE TITLE
Error when finding code cave

### ISSUE THREAD

**Issue by picheljitsu** [secretsquirrel/the-backdoor-factory#77]
Sorry, I don't have time to dig into this and figure out what's going on. I'm kind of on a deadline, but figured I'd submit this real quick. 

`[*] Checking if binary is supported
[*] Gathering file info
[*] Reading win64 entry instructions
Looking for caves with a size of 380 bytes (measured as an integer
[*] Looking for caves
We have a winner: .data
->Begin Cave 0x68061d
->End of Cave 0x680960
Size of Cave (int) 835
SizeOfRawData 0x1ea00
PointerToRawData 0x663600
End of Raw Data: 0x682000
**************************************************
No section
->Begin Cave 0x70f263
->End of Cave 0x70f408
Size of Cave (int) 421
**************************************************
[*] Total of 2 caves found
Traceback (most recent call last):
  File "backdoor.py", line 62, in <module>
    class bdfMain():
  File "backdoor.py", line 612, in bdfMain
    print "File {0} is in the 'backdoored' directory".format(os.path.basename(supported_file.OUTPUT))
  File "/usr/lib/python2.7/posixpath.py", line 114, in basename
    i = p.rfind('/') + 1
AttributeError: 'NoneType' object has no attribute 'rfind'
`

**Comment by secretsquirrel** [comment]
Thanks for using BDF. I'm sorry you didn't have time to look into this further. Lucky for you as an open source dev I have nothing but free time!

So the error is in Python itself. But without knowing the snowflake of an operating system you are using and what binary you were attempting to patch I can't repo.

To reproduce I need the following:
1. Output from uname -a
2. A link to the binary causing the issue.

**Comment by secretsquirrel** [comment]
No response. Closing issue.

**Comment by secretsquirrel** [comment]
fixed: https://github.com/secretsquirrel/the-backdoor-factory/commit/d144cc29e6ee849b072cef3594354814ce13be82
